backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "products"
    extension: "json"
    format: "json"
    create: true
    slug: "{{slug}}"
    identifier_field: "name"
    fields:
      - label: "שם המוצר"
        name: "name"
        widget: "string"
      - label: "מחיר (ליחידה/ק״ג)"
        name: "price"
        widget: "number"
        value_type: "float"
        step: 0.01
      - label: "שקיל"
        name: "is_weighted"
        widget: "boolean"
